name: dashboard
recipe: laravel

proxy:
  appserver_nginx:
    - dashboard.lndo.site
  mailhog:
    - mail.lndo.site

services:
  database:
    portforward: 3307
  node:
    type: node:24
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
  myservice:
    type: phpmyadmin:5.2
tooling:
  npm:
    service: node
  node:
    service: node

config:
  via: nginx
  php: "8.2"
  composer_version: 2-latest
  xdebug: false
  webroot: public
  database: mariadb:10.5
