# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: dashboard

# The type of the application to build.
type: php:8.2

build:
    flavor: none

dependencies:
    nodejs:
        npm: ^10
    php:
        composer/composer: ^2

variables:
    env:
        # https://github.com/nvm-sh/nvm/releases
        NVM_VERSION: v0.39.7
        # https://nodejs.org/en/about/previous-releases
        NODE_VERSION: v18.19.1

# The hooks that will be performed when the package is deployed.
hooks:
    build: |
        set -e

        rm public/.htaccess

        composer install --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader
        php artisan config:clear
        php artisan clear-compiled
        php artisan storage:link

        # https://docs.platform.sh/languages/nodejs/node-version.html#use-nvm
        unset NPM_CONFIG_PREFIX
        export NVM_DIR="$PLATFORM_APP_DIR/.nvm"

        # Link cache with app
        if [ ! -d "$PLATFORM_CACHE_DIR/.nvm" ]; then
            mkdir -p $PLATFORM_CACHE_DIR/.nvm
        fi
        ln -s $PLATFORM_CACHE_DIR/.nvm $NVM_DIR

        # Check for Node.js version and install if not present
        if [ ! -d "$PLATFORM_CACHE_DIR/.nvm/versions/node/$NODE_VERSION" ]; then

            # Get nvm install script if correct version not present
            export NVM_INSTALL_FILE="${PLATFORM_CACHE_DIR}/nvm_${NVM_VERSION}_install.sh"
            if [ ! -f "$NVM_INSTALL_FILE" ]; then
                wget -nc -O "$NVM_INSTALL_FILE" "https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh"
            fi

            # Install, automatically using NODE_VERSION
            bash $NVM_INSTALL_FILE
        fi

        # Activate nvm
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

        # Use the specified version
        nvm use "$NODE_VERSION" 

        # npm cache clean --force
        npm ci
        npm run build
    deploy: |
        set -e
        php artisan clear-compiled
        php artisan config:cache
        php artisan route:trans:cache
        php artisan view:cache
        php artisan migrate --force
        php artisan google-fonts:fetch

crons:
    generate-statistics:
        # once per day at 00:55
        spec: "55 0 1 * *"
        cmd: |
            if [ "$PLATFORM_BRANCH" = main ]; then
                php artisan statistics
            fi
    capture-kpis:
        # once per day at 01:20
        spec: "20 1 * * *"
        cmd: |
            if [ "$PLATFORM_BRANCH" = main ] || [ "$PLATFORM_BRANCH" = dev ]; then
                php artisan kpis
            fi
    capture-writing-streak-kpi:
        # once per day at 02:20
        spec: "20 2 * * *"
        cmd: |
            if [ "$PLATFORM_BRANCH" = main ] || [ "$PLATFORM_BRANCH" = dev ]; then
                php artisan writing-streak-kpi
            fi
    hubspot-missing-sync:
        # once per hour at 05
        spec: "05 * * * *"
        cmd: |
            if [ "$PLATFORM_BRANCH" = main ]; then
                php artisan hubspot:sync
            fi
    hubspot-full-sync:
        # once per day at 03:20
        spec: "20 3 * * *"
        cmd: |
            if [ "$PLATFORM_BRANCH" = main ]; then
                php artisan hubspot:sync --f
            fi
    posthog-sync:
        # once per day at 04:20
        spec: "20 4 * * *"
        cmd: |
            if [ "$PLATFORM_BRANCH" = main ] || [ "$PLATFORM_BRANCH" = dev ]; then
                php artisan posthog:sync
            fi
    api-full-sync:
        # once per day at 05:20
        spec: "20 5 * * *"
        cmd: |
            if [ "$PLATFORM_BRANCH" = main ]; then
                php artisan nlp_api:sync
            fi
    snapshot-once-per-day:
        # once per day at 12:00
        spec: "0 12 * * *"
        cmd: |
            if [ "$PLATFORM_BRANCH" = main ]; then
                platform backup:create --yes --no-wait --live
            fi

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "rdbms:mysql"

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "storage/app/public": "shared:files/public"
    "storage/app/purifier": "shared:files/purifier"
    "storage/framework/views": "shared:files/views"
    "storage/framework/sessions": "shared:files/sessions"
    "storage/framework/cache": "shared:files/cache"
    "storage/logs": "shared:files/logs"
    "bootstrap/cache": "shared:files/bootstrap/cache"
    "/.config": "shared:files/config"

# The configuration of app when it is exposed to the web.
web:
    commands:
        start: php artisan clear-compiled && php artisan config:cache && /usr/sbin/php-fpm8.2
    locations:
        "/":
            root: "public"
            index:
                - index.php
            headers:
                Strict-Transport-Security: max-age=31536000; includeSubDomains
                X-Frame-Options: SAMEORIGIN
                X-XSS-Protection: "1; mode=block"
                X-Content-Type-Options: nosniff
                Content-Security-Policy: "object-src 'none' upgrade-insecure-requests form-action 'self' frame-ancestors 'self'"
                Referrer-Policy: strict-origin-when-cross-origin
            allow: true
            passthru: "/index.php"
            rules:
                "^/(css|js)/app.(css|js)":
                    expires: 2m

workers:
    queue:
        size: "S"
        commands:
            start: |
                php artisan queue:work --tries=100 --queue=high,medium,low,default
        disk: 256
        relationships:
            database: "rdbms:mysql"
