version: '3.9'

services:
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./ops/nginx/Dockerfile
  #   ports:
  #     - "8080:80"

  dashboard:
    build:
      context: .
      dockerfile: ./ops/dashboard/Dockerfile
    volumes:
      - dashboard_data:/var/www/html/storage
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=dashboard
      - DB_USERNAME=dashboard
      - DB_PASSWORD=dashboard
      - DB_SSLMODE=disable
      - MYSQL_ATTR_SSL_CA=""
      # generated via php artisan key:generate --show
      - APP_KEY=base64:N7kLZR5gKHHPJ0VEPWUYRKkgLQjRpz7RojP1DpIcc+E=
    restart: always
    ports:
      - "8080:80"


  mysql:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dashboard
      MYSQL_USER: dashboard
      MYSQL_PASSWORD: dashboard
    restart: always

volumes:
  db_data: {}
  dashboard_data: {}
